ez_content_create_no_draft:
    path: /content/create/nodraft/{contentTypeId}/{language}/{parentLocationId}
    defaults:
        _controller: EzSystemsRepositoryFormsBundle:ContentEdit:createWithoutDraft

ez_content_create:
    path: /content/create/{contentTypeId}/{language}/{parentLocationId}
    defaults:
        _controller: EzSystemsRepositoryFormsBundle:ContentEdit:create

ez_content_edit:
    path: /content/update/{contentId}/{version}/{language}
    defaults:
        _controller: EzSystemsRepositoryFormsBundle:ContentEdit:edit
